### ISSUE TITLE
Is there a way to remove separator line between the 2 rows?

### ISSUE THREAD

**Issue by ozitrance** [EurekaCommunity/SplitRow#19]
I can remove the separator lines from the top and bottom of the rows using:

        self.tableView?.separatorStyle = .none

But it doesn't remove the lines between the 2 rows in the splitRow row..

Any ideas?

BTW Thanks a lot for this very useful row!

**Comment by marbetschar** [comment]
The property you want to modify your s the leftSeparatorStyle of the tableWievRight:
https://github.com/EurekaCommunity/SplitRow/blob/d98349a5da4d1a2e78783f7cc169502179ce5ca2/SplitRow/SplitRowCell.swift#L30

Setting this to .none should result in the desired behaviour. However, I‘m not sure if you are able to access it yet, due to the access scope now.

Unfortunately I do not have my Mac with me to digg into right now, but pull requests are very welcome.

**Comment by ozitrance** [comment]
Thank you @marbetschar!

I think you're right, I couldn't get to it - I will look into it and see if I can figure out the changes needed to make it accessible... It looked a little too complicated for me at first glance but I'll try again! For now changing it in the source code is good enough. Thanks!
